baseURL = 'https://DayeLim.github.io/'
languageCode = 'en-us'
title = 'DAYE LIM (임다예)'
theme = 'hermit'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[author]
  name = 'Daye Lim'

[params]
  homeSubtitle1 = """Post-doc"""
  homeSubtitle2 = """Solar Influences Data Analysis Center, Royal Observatory of Belgium"""
  homeSubtitle3 = """Centre for mathematical Plasma-Astrophysics, KU Leuven"""

  customCSS = ["css/custom.css"]
  
[menu]

  [[menu.main]]
    name = "Curriculum Vitae"
    url = "curriculum_vitae/"
    weight = 10
  
  [[menu.main]]
    name = "Publications"
    url = "publications/"
    weight = 20

  [[menu.main]]
    name = "Major Solar Flare Probability Forecast Board"
    url = "https://dayelim.github.io/MajorSolarFlareForecastBoard/"
    weight = 30